/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cityclub;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahlame SEHLAOUI
 */
public class reglement extends javax.swing.JFrame {

    public String nom ;
    public String prenom;
    public int recus ;
    public double montantapaye;
    public int ID;
    public reglement(String nom,String prenom, int recus ,double montantapaye,int id) {
        this.nom =nom;
        this.prenom=prenom;
        this.montantapaye =montantapaye ;
        this.recus =recus ;
        this.ID=id;
        initComponents();
        this.setLocationRelativeTo(this);
        affichage() ;
    }
    // Traitement de GUI pour reglement 
    public void  affichage(){
        String completeName = this.nom+" "+this.prenom;
        this.lbl_fullName.setText(completeName.toUpperCase());
        this.lbl_apayé.setText(String.valueOf(this.montantapaye));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_fullName = new javax.swing.JLabel();
        btn_updateRestPaye = new javax.swing.JPanel();
        btn_reglerR = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_apayé = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_montant = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lbl_restpayé = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(228, 67, 13));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Réglement");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 530, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lbl_fullName.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 24)); // NOI18N
        lbl_fullName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_fullName.setText("SEHLAOUI HOUSSAM EDDINE ");

        btn_updateRestPaye.setBackground(new java.awt.Color(204, 204, 204));
        btn_updateRestPaye.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(204, 51, 0)));
        btn_updateRestPaye.setForeground(new java.awt.Color(204, 51, 0));
        btn_updateRestPaye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateRestPayeMouseClicked(evt);
            }
        });

        btn_reglerR.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        btn_reglerR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_reglerR.setText("REGLER");
        btn_reglerR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_reglerRMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_updateRestPayeLayout = new javax.swing.GroupLayout(btn_updateRestPaye);
        btn_updateRestPaye.setLayout(btn_updateRestPayeLayout);
        btn_updateRestPayeLayout.setHorizontalGroup(
            btn_updateRestPayeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_reglerR, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
        );
        btn_updateRestPayeLayout.setVerticalGroup(
            btn_updateRestPayeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_reglerR, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jLabel4.setText("< Annuler");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        jLabel5.setText("A payer :");

        lbl_apayé.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 48)); // NOI18N
        lbl_apayé.setForeground(new java.awt.Color(255, 204, 153));
        lbl_apayé.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_apayé.setText("1200");

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 36)); // NOI18N
        jLabel7.setText("DH");

        txt_montant.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        txt_montant.setText("0");
        txt_montant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_montantActionPerformed(evt);
            }
        });
        txt_montant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_montantKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_montantKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_montantKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel8.setText("Restant a payer :");

        lbl_restpayé.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbl_restpayé.setForeground(new java.awt.Color(228, 67, 13));
        lbl_restpayé.setText("10");

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel10.setText("DH");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_fullName, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_apayé, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(84, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_montant, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_restpayé, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn_updateRestPaye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lbl_fullName, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_apayé, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addComponent(txt_montant, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_restpayé, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_updateRestPaye, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 530, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_montantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_montantActionPerformed
        
    }//GEN-LAST:event_txt_montantActionPerformed

    private void txt_montantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_montantKeyTyped
        
    }//GEN-LAST:event_txt_montantKeyTyped

    private void txt_montantKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_montantKeyPressed
        if (txt_montant.getText().compareTo("")==0){
            txt_montant.setText("0");
        }
        double montant = Double.valueOf(txt_montant.getText());
        double apayé = Double.valueOf(lbl_apayé.getText());
        double rest = apayé -montant ;
        lbl_restpayé.setText(String.valueOf(rest));
    }//GEN-LAST:event_txt_montantKeyPressed

    private void txt_montantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_montantKeyReleased
        if (txt_montant.getText().compareTo("")==0){
            txt_montant.setText("0");
        }
        double montant = Double.valueOf(txt_montant.getText());
        double apayé = Double.valueOf(lbl_apayé.getText());
        double rest = apayé -montant ;
        lbl_restpayé.setText(String.valueOf(rest));
    }//GEN-LAST:event_txt_montantKeyReleased

    private void btn_updateRestPayeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateRestPayeMouseClicked
//         String query ="UPDATE `payement` SET `restPayé`="+getNewRest()+" WHERE `recus`="+this.recus;
//        try {
//            executeSQLQuery(query ,"update assi houssam");
//        } catch (SQLException ex) {
//            Logger.getLogger(reglement.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btn_updateRestPayeMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.hide();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void btn_reglerRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reglerRMouseClicked
        double montant = Double.valueOf(txt_montant.getText());
        double apayé = Double.valueOf(lbl_apayé.getText());
        double newMApaye = apayé +montant ;
        // requete pour la table payement 
        String query ="INSERT INTO `payement`(`recus`, `ID_MP`, `datePay`, `montantPayéP`) VALUES ("+this.recus+","+this.ID+",DATE( NOW()),"+txt_montant.getText()+")";
        // requete pour la table des abonnement 
        String queryAB = "UPDATE `abonnement` SET `MontantPayé`="+newMApaye+" WHERE`recus`="+this.recus;
        Connection con = getConnection();
        Statement st1 ;
        Statement st2 ;
        try{
            st1 =(Statement) con.createStatement();
            if(st1.executeUpdate(queryAB)==1 ){
                JOptionPane.showMessageDialog(null,"payement is Succefully update");
                this.hide();
            } else {
                JOptionPane.showMessageDialog(null,"payement is not Succefully update");
            }
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_reglerRMouseClicked

    public Connection getConnection(){
        Connection con ;
        try{
            con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3324/gym", "root", "");
            return con ;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }
    public void executeSQLQuery(String query ,String message) throws SQLException{
        Connection con = getConnection();
        Statement st ;
        try{
            st =(Statement) con.createStatement();
            if(st.executeUpdate(query)==1){
                JOptionPane.showMessageDialog(null,"Data"+ message+"Succefully");
            } else {
                JOptionPane.showMessageDialog(null,"Data not"+ message);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    public double getNewRest(){                                       
        if (txt_montant.getText().compareTo("")==0){
            txt_montant.setText("0");
        }
        double montant = Double.valueOf(txt_montant.getText());
        double apayé = Double.valueOf(lbl_apayé.getText());
        double rest = apayé -montant ;
        return rest ;
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_reglerR;
    private javax.swing.JPanel btn_updateRestPaye;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_apayé;
    private javax.swing.JLabel lbl_fullName;
    private javax.swing.JLabel lbl_restpayé;
    private javax.swing.JTextField txt_montant;
    // End of variables declaration//GEN-END:variables
}
